version: "3"

services:
  database:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - "POSTGRES_PASSWORD=password"
    volumes:
      - ./dc/database/data:/var/lib/postgresql/data
    ports:
      - 8080:5432

  api:
    build:
      context: ./
      dockerfile: Dockerfile.Api
    depends_on:
      database:
        condition: service_healthy
    environment:
      - "Database__Host=database"
      - "Database__Port=5432"
      - "Database__Database=agrigate"
      - "Database__Username=postgres"
      - "Database__Password=password"
      - "Api__ApiService__HostName=api"
      - "Api__ApiService__Port=5001"
      - "Api__EventService__ServiceName=EventService"
      - "Api__EventService__HostName=eventservice"
      - "Api__EventService__SupervisorName=EventSupervisor"
      - "Api__EventService__Port=5000"
      - "Notifications__ClientId=clientId"
      - "Notifications__Host=host"
      - "Notifications__Port=1234"
      - "Notifications__Username=username"
      - "Notifications__Password=password"
      - "Notifications__SecureConnection=true"
    ports:
      - 8081:8081

  eventservice:
    build:
      context: ./
      dockerfile: Dockerfile.EventService
    depends_on:
      - api
    environment:
      - "Telemetry__ClientId=clientId"
      - "Telemetry__Host=host"
      - "Telemetry__Port=1234"
      - "Telemetry__Topic=topic"
      - "Telemetry__Username=username"
      - "Telemetry__Password=password"
      - "Telemetry__SecureConnection=true"
      - "Database__Host=database"
      - "Database__Port=5432"
      - "Database__Database=agrigate"
      - "Database__Username=postgres"
      - "Database__Password=password"
      - "Service__ServiceName=EventService"
      - "Service__HostName=eventservice"
      - "Service__Port=5000"
    expose:
      - 1234
