using MQTTnet.Client;

namespace Agrigate.Core.Services.MqttService;

/// <summary>
/// Wrapper service for MqttFactory so MqttActors can be tested
/// </summary>
public interface IMqttService
{
    /// <summary>
    /// Returns an MqttClient generated by MqttFactory
    /// </summary>
    /// <returns></returns>
    IMqttClient CreateMqttClient();

    /// <summary>
    /// Returns the MqttClientSubscribeOptionsBuilder from MqttFactory
    /// </summary>
    /// <returns></returns>
    MqttClientSubscribeOptionsBuilder CreateSubscribeOptionsBuilder();
}